question_data = [{"category": "Animals", "type": "boolean", "difficulty": "easy",
                  "question": "The Axolotl is an amphibian that can spend its whole life in a larval state.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
                  "question": "In the 1988 film &quot;Akira&quot;, Tetsuo ends up destroying Tokyo.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Mythology", "type": "boolean", "difficulty": "easy",
                  "question": "In Norse mythology, Thor once dressed as a woman.", "correct_answer": "True",
                  "incorrect_answers": ["False"]}, {"category": "Animals", "type": "boolean", "difficulty": "easy",
                                                    "question": "A slug&rsquo;s blood is green.",
                                                    "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "Greenland is almost as big as Africa.", "correct_answer": "False",
                  "incorrect_answers": ["True"]}, {"category": "History", "type": "boolean", "difficulty": "easy",
                                                   "question": "The Tiananmen Square protests of 1989 were held in Hong Kong.",
                                                   "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
                  "question": "A universal set, or a set that contains all sets, exists.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
                  "question": "The book 1984 was published in 1949.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "Nutella is produced by the German company Ferrero.", "correct_answer": "False",
                  "incorrect_answers": ["True"]}, {"category": "Politics", "type": "boolean", "difficulty": "easy",
                                                   "question": "In 2016, the United Kingdom voted to stay in the EU.",
                                                   "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "Donkey Kong was originally set to be a Popeye arcade game.", "correct_answer": "True",
                  "incorrect_answers": ["False"]}, {"category": "History", "type": "boolean", "difficulty": "easy",
                                                    "question": "The United States Department of Homeland Security was formed in response to the September 11th attacks.",
                                                    "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                  "question": "In the original script of &quot;The Matrix&quot;, the machines used humans as additional computing power instead of batteries.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "easy",
                  "question": "A bear does NOT defecate during hibernation. ", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
                  "question": "The anime &quot;Lucky Star&quot; follows the story of one girl who is unaware she is God.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "Ada Lovelace is often considered the first computer programmer.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "You can legally drink alcohol while driving in Mississippi.", "correct_answer": "True",
                  "incorrect_answers": ["False"]}, {"category": "History", "type": "boolean", "difficulty": "easy",
                                                    "question": "United States President John F. Kennedy was assassinated during his presidential motorcade in Atlanta, Georgia on November 22nd, 1963.",
                                                    "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "Minecraft can be played with a virtual reality headset.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                  "question": "Ewan McGregor did not know the name of the second prequel film of Star Wars during and after filming.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                  "question": "In Alfred Hitchcock&#039;s film &#039;Psycho&#039; it is said he used chocolate syrup to simulate the blood in the famous shower scene from ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "The United States of America declared their independence from the British Empire on July 4th, 1776.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                  "question": "The alternative rock band, They Might Be Giants, released their album &#039;Flood&#039; in 1990. ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Comics", "type": "boolean", "difficulty": "easy",
                  "question": "The &quot;Pepe&quot; meme originated from a comic drawn by Matt Furie called &quot;Boy&#039;s Club&quot;?",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "In Sonic the Hedgehog universe, Tails&#039; real name is Miles Prower.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Sports", "type": "boolean", "difficulty": "easy",
                  "question": "Roger Federer is a famous soccer player.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "Time on Computers is measured via the EPOX System.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "In the game Dead by Daylight, the killer Michael Myers is refered to as &quot;The Shape&quot;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "California is larger than Japan.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                  "question": "George Lucas directed the entire original Star Wars trilogy.", "correct_answer": "False",
                  "incorrect_answers": ["True"]}, {"category": "History", "type": "boolean", "difficulty": "easy",
                                                   "question": "In World War ll, Great Britian used inflatable tanks on the ports of Great Britain to divert Hitler away from Normandy\/D-day landing.",
                                                   "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "In RuneScape, one must complete the &quot;Dragon Slayer&quot; quest before equipping Rune Platelegs.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Politics", "type": "boolean", "difficulty": "easy",
                  "question": "Donald Trump won the popular vote in the 2016 United States presidential election.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "In Heroes of the Storm, the Cursed Hollow map gimmick requires players to kill the undead to curse the enemy team.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "&quot;Metal Gear Solid 3: Snake Eater&quot; was released in 2004.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
                  "question": "The sum of any two odd integers is odd.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "Several characters in &quot;Super Mario 64&quot; blink their eyes, including Mario himself.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "New Haven is the capital city of the state of Connecticut in the United States.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                  "question": "Michael Jackson wrote The Simpsons song &quot;Do the Bartman&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Politics", "type": "boolean", "difficulty": "easy",
                  "question": "Former president Theodore Roosevelt (1900-1908)  ran for another term under the Progressive Party in 1912.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Vehicles", "type": "boolean", "difficulty": "easy",
                  "question": "BMW M GmbH is a subsidiary of BMW AG that focuses on car performance.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                  "question": "The 2011 movie &quot;The Adventures of Tintin&quot; was directed by Steven Spielberg.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
                  "question": "A scalene triangle has two sides of equal length.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "A pasodoble is a type of Italian pasta sauce.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                  "question": "John Williams composed the music for &quot;Star Wars&quot;.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "In Until Dawn, both characters Sam and Mike cannot be killed under any means until the final chapter of the game.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "In the video game &quot;Splatoon&quot;, the playable characters were originally going to be rabbits instead of squids.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "&quot;Resident Evil 7&quot; is the first first-person Resident Evil game.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "The shotgun appears in every numbered Resident Evil game.", "correct_answer": "True",
                  "incorrect_answers": ["False"]}]
